.\" Copyright (c) 2012 - Matthew Fischer
.TH accomplishments-viewer 1 "20 October 2012"
.SH NAME
accomplishments-viewer \- the viewer for the Ubuntu Accomplishments system
.SH SYNOPSIS
.B accomplishments-viewer
[
.I OPTION
]
.SH DESCRIPTION
.B accomplishments-viewer
the viewer for the Ubuntu Accomplishments system.
.SH OPTIONS
.TP
.B \-h, \-\-help
Show help options
.TP
.B \-v, \-\-verbose
Show debug messages on STDOUT.
.TP
.B \-\-vv
Show debug messages for accomplishments_viewer_lib on STDOUT.
.TP
.B \-a ID, \-\-accomplishment=ID
Display information about the provided accomplishment ID.
.SH SEE ALSO
.TP
.B accomplishments-daemon (1)
.sp
.LP
